In [1]:
# 1、导入numpy库并简写为 np (★☆☆)
import numpy as np

In [2]:
# 2、打印numpy的版本和配置说明 (★☆☆)
# (提示: np.__version__, np.show_config)
print(np.__version__)
np.show_config()

1.16.4
mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/root/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/root/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/root/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/root/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/root/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/root/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/root/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/root/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/root/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', Non

In [3]:
# 3、创建一个长度为10的空向量 (★☆☆)
# (提示: np.__version__, np.show_config)
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
# 4、如何找到任何一个数组的内存大小？ (★☆☆)
# (提示: size, itemsize)
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [7]:
# 5、如何从命令行得到numpy中add函数的说明文档? (★☆☆)
# (提示: np.info)
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [8]:
# 6、创建一个长度为10并且除了第五个值为1的空向量 (★☆☆)
# (提示: array[4])
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [9]:
# 7、创建一个值域范围从10到49的向量(★☆☆)
# (提示: np.arange)
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [10]:
# 8、反转一个向量(第一个元素变为最后一个) (★☆☆)
# (提示: array[::-1])
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [18]:
# 9、创建一个 3x3 并且值从0到8的矩阵(★☆☆)
# (提示: reshape)
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
# 10、找到数组[1,2,0,0,4,0]中非0元素的位置索引 (★☆☆)
# (提示: np.nonzero)
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


In [15]:
# 11、 创建一个 3x3 的单位矩阵 (★☆☆)
# (提示: np.eye)
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
# 12、创建一个 3x3x3的随机数组 (★☆☆)
# (提示: np.random.random)
Z = np.random.random((3,3,3))
print(Z)

[[[0.87191157 0.57512943 0.83032167]
  [0.53615758 0.94713974 0.59020037]
  [0.05885201 0.4345791  0.38950625]]

 [[0.62378262 0.41689476 0.32274515]
  [0.46045735 0.46115481 0.3010286 ]
  [0.15725799 0.08238952 0.80463761]]

 [[0.7665484  0.38981558 0.9655716 ]
  [0.59158786 0.76878119 0.90158346]
  [0.52533247 0.11541416 0.41967277]]]


In [20]:
# 13、创建一个 10x10 的随机数组并找到它的最大值和最小值 (★☆☆)
# (提示: min, max)
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.007840211464993696 0.9907508129752284


In [21]:
# 14、创建一个长度为30的随机向量并找到它的平均值 (★☆☆)
# (提示: mean)
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5923872019234917


In [22]:
# 15、创建一个二维数组，其中边界值为1，其余值为0 (★☆☆)
# (提示: array[1:-1, 1:-1])
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [23]:
# 16、对于一个存在在数组，如何添加一个用0填充的边界? (★☆☆)
# (提示: np.pad)
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [24]:
# 17、以下表达式运行的结果分别是什么? (★☆☆)
# (提示: NaN = not a number, inf = infinity)
# 0 * np.nan
# np.nan == np.nan
# np.inf > np.nan
# np.nan - np.nan
# 0.3 == 3 * 0.1
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [27]:
# 18、创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置 (★☆☆)
# (提示: np.diag)
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [28]:
# 19、创建一个8x8 的矩阵，并且设置成棋盘样式 (★☆☆)
# (提示: array[::2])
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [29]:
# 20、考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么?
# (提示: np.unravel_index)
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [30]:
# 21、用tile函数去创建一个 8x8的棋盘样式矩阵(★☆☆)
# (提示: np.tile)
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [32]:
# 22、对一个5x5的随机矩阵做归一化(★☆☆)
# (提示: (x - min) / (max - min))
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.19180458 0.31395565 0.96459858 0.8482455  0.74702292]
 [0.73532713 0.86067298 0.40608072 0.85793782 0.72492535]
 [0.         1.         0.52208849 0.21376729 0.64354082]
 [0.7034953  0.52776407 0.23379578 0.4083149  0.9408554 ]
 [0.27137968 0.64928037 0.53033739 0.99887492 0.41596727]]


In [34]:
# 23、创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype？(★☆☆)
# (提示: np.dtype)
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [35]:
# 24、一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？ (★☆☆)
# (提示: np.dot | @)
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [36]:
# 25、给定一个一维数组，对其在3到8之间的所有元素取反 (★☆☆)
# (提示: >, <=)
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [46]:
# 26、下面脚本运行后的结果是什么? (★☆☆)
# (提示: np.sum)
# print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10


In [60]:
# 27、考虑一个整数向量Z,下列表达合法的是哪个? (★☆☆)
# Z**Z
# 2 << Z >> 2
# Z <- Z
# 1j*Z
# Z/1/1
# Z<Z>Z
Z = np.arange(5)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
Z<Z>Z

[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [64]:
# 28、下列表达式的结果分别是什么?(★☆☆)
# np.array(0) / np.array(0)
# np.array(0) // np.array(0)
# np.array([np.nan]).astype(int).astype(float)
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/root/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in true_divide
  """
/root/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in floor_divide
  


In [65]:
# 29、如何从零位对浮点数组做舍入 ? (★☆☆)
# (提示: np.uniform, np.copysign, np.ceil, np.abs)
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[-2.  2.  1. 10. -7.  3.  1.  2. -6.  5.]


In [67]:
# 30、如何找到两个数组中的共同元素? (★☆☆)
# (提示: np.intersect1d)
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[3 4 5 6 9]


In [73]:
# 31、如何忽略所有的 numpy 警告(尽管不建议这么做)? (★☆☆)
# (提示: np.seterr, np.errstate)
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

In [75]:
# 32、下面的表达式是正确的吗? (★☆☆)
# (提示: imaginary number)
# np.sqrt(-1) == np.emath.sqrt(-1)
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


/root/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in sqrt
  after removing the cwd from sys.path.


In [76]:
# 33、如何得到昨天，今天，明天的日期? (★☆☆)
# (提示: np.datetime64, np.timedelta64)
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2019-08-07
Today is 2019-08-08
Tomorrow is 2019-08-09


In [77]:
# 34、如何得到所有与2016年7月对应的日期？ (★★☆)
# (提示: np.arange(dtype=datetime64['D']))
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [81]:
# 35、如何直接在位计算(A+B)\*(-A/2)(不建立副本)? (★★☆)
# (提示: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [82]:
# 36、用五种不同的方法去提取一个随机数组的整数部分(★★☆)
# (提示: %, np.floor, np.ceil, astype, np.trunc)
Z = np.random.uniform(0,10,10)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[1. 9. 5. 5. 1. 2. 6. 8. 2. 3.]
[1. 9. 5. 5. 1. 2. 6. 8. 2. 3.]
[1. 9. 5. 5. 1. 2. 6. 8. 2. 3.]
[1 9 5 5 1 2 6 8 2 3]
[1. 9. 5. 5. 1. 2. 6. 8. 2. 3.]


In [83]:
# 37、创建一个5x5的矩阵，其中每行的数值范围从0到4 (★★☆)
# (提示: np.arange)
Z = np.zeros((5,5))
Z += np.arange(5)
print (Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [84]:
# 38、通过考虑一个可生成10个整数的函数，来构建一个数组(★☆☆)
# (提示: np.fromiter)
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [85]:
# 39、创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1 (★★☆)
# (提示: np.linspace)
Z = np.linspace(0,1,11,endpoint=False)[1:]
print (Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [86]:
# 40、创建一个长度为10的随机向量，并将其排序 (★★☆)
# (提示: sort)
Z = np.random.random(10)
Z.sort()
print (Z)

[0.10821638 0.24311713 0.26129488 0.330083   0.42700575 0.5020115
 0.52475285 0.57725124 0.78625879 0.89742326]


In [87]:
# 41、对于一个小数组，如何用比 np.sum更快的方式对其求和？(★★☆)
# (提示: np.add.reduce)
Z = np.arange(10)
np.add.reduce(Z)

45

In [89]:
# 42、对于两个随机数组A和B，检查它们是否相等(★★☆)
# (提示: np.allclose, np.array_equal)
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# 方法2
# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


In [90]:
# 43、创建一个只读数组(read-only) (★★☆)
# (提示: flags.writeable)
# 使用如下过程实现
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

In [91]:
# 44、将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式(★★☆)
# (hint: np.sqrt, np.arctan2)
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print (R)
print (T)

[1.23400427 0.84686669 0.63712224 0.88822765 0.87527027 0.78750975
 0.86527883 0.67766636 0.23635736 0.26850963]
[0.93252767 0.83928491 0.29026708 1.27283765 0.64682852 0.34024574
 0.74408176 1.16380654 0.07922472 0.7448537 ]


In [92]:
# 45、创建一个长度为10的向量，并将向量中最大值替换为1 (★★☆)
# (提示: argmax)
Z = np.random.random(10)
Z[Z.argmax()] = 0
print (Z)

[0.         0.02854083 0.86921929 0.16966175 0.31755916 0.9259184
 0.12546309 0.53285483 0.49971159 0.62776064]


In [93]:
# 46、创建一个结构化数组，并实现 x 和 y 坐标覆盖 [0,1]x[0,1] 区域 (★★☆)
# (提示: np.meshgrid)
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [94]:
# 47、给定两个数组X和Y，构造Cauchy矩阵C (Cij =1/(xi - yj))
# (提示: np.subtract.outer)
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


In [96]:
# 48、打印每个numpy标量类型的最小值和最大值？ (★★☆)
# (提示: np.iinfo, np.finfo, eps)
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [100]:
# 49、如何打印一个数组中的所有数值? (★★☆)
# (提示: np.set_printoptions)
np.set_printoptions()
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [101]:
# 50、给定标量时，如何找到数组中最接近标量的值？(★★☆)¶
# (提示: argmin)
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print (Z[index])

86


In [102]:
# 51、创建一个表示位置(x,y)和颜色(r,g,b)的结构化数组(★★☆)
# (提示: dtype)
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print (Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [ ]:
# 52、对一个表示坐标形状为(100,2)的随机向量，找到点与点的距离(★★☆)
# (提示: np.atleast_2d, T, np.sqrt)
# Z = np.random.random((10,2))
# X,Y = np.atleast_2d(Z[:,0], Z[:,1])
# D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
# print(D)

# 方法2
# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

In [ ]:
53、